### PR TITLE
Rebuild python311 0 1 hfa4d84

### PR DESCRIPTION
**Pull request by yarikoptic**
This is https://github.com/conda-forge/annexremote-feedstock/pull/38 (can't push there) but with

- fixup of tests for pythons 3.10 and 3.11
- me added as maintainer

"urgency": blocks building datalad for 3.11
 
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yarikoptic** [comment]
it would need magical "click green button" by @notestaff or someone else with authority.

**Review by zklaus — APPROVED** [review]
@conda-forge/core could you step in here and merge to add @yarikoptic to the maintainers? He has tried contacting the current sole maintainer here, in conda-forge/git-annex-feedstock#152, and via email for a few months.

**Comment by yarikoptic** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
This package should probably be made no arch.

You can now be specific about Unix/windows with no arch.

**Pull request merged**
